# Generated by Django 3.1.5 on 2021-01-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='url',
            field=models.URLField(),
        ),
    ]
