# Generated by Django 3.1.5 on 2021-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210110_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
