# Generated by Django 3.1.5 on 2021-01-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_flat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
