# Generated by Django 3.1.5 on 2021-01-24 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210121_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.IntegerField(),
        ),
    ]
