# Generated by Django 3.1.5 on 2021-01-24 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210124_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SearchingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('results', models.ManyToManyField(to='main.Flat')),
            ],
        ),
    ]
