# Generated by Django 3.1.5 on 2021-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210124_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchingresult',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
