# Generated by Django 3.1.5 on 2021-01-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210124_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchingresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
