# Generated by Django 3.1.5 on 2021-01-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_flat_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchingresult',
            name='date',
        ),
    ]
