# Generated by Django 3.1.5 on 2021-01-27 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_searchingresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SearchingResult',
        ),
    ]
