# Generated by Django 3.1.5 on 2021-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_watchedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flat',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flat',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flat',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
