# Generated by Django 3.1.5 on 2021-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='refresh_token',
            field=models.CharField(max_length=2000),
        ),
    ]
